TebLocalPlannerROS:

 odom_topic: odom
 map_frame: /map
    
 # Trajectory
  
 teb_autosize: True
 dt_ref: 0.2
 dt_hysteresis: 0.03
 min_samples : 3
 global_plan_overwrite_orientation: False
 max_global_plan_lookahead_dist: 5
 feasibility_check_no_poses: 3
    
 # Robot
         
 max_vel_x: 1.0
 max_vel_x_backwards: 0.6
 max_vel_theta: 0.5
 acc_lim_x: 1.0
 acc_lim_theta: 0.2
 min_turning_radius: 2.6 #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
   type: "polygon"
   vertices: [[-0.3, -0.5], [1.3, -0.5], [1.3, 0.5], [-0.3, 0.5]] # for type "line"

 # GoalTolerance
    
 xy_goal_tolerance: 0.1
 yaw_goal_tolerance: 0.1
 free_goal_vel: False
    
 # Obstacles
    
 min_obstacle_dist: 0.1
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 30
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 # Optimization
    
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.0001 #!!!!! 
 weight_max_vel_x: 1.0 #2
 weight_max_vel_theta: 1.0 #1
 weight_acc_lim_x: 1.0 #1
 weight_acc_lim_theta: 1.0 #1
 weight_kinematics_nh: 1000
 weight_kinematics_forward_drive: 1.0
 weight_kinematics_turning_radius: 1.0
 weight_optimaltime: 2.0
 weight_obstacle: 50.0
 weight_dynamic_obstacle: 10 # not in use yet
 selection_alternative_time_cost: False

 # Homotopy Class Planner

 enable_homotopy_class_planning: False
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False
